AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"

  DisplayCopNames: true

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30

Layout/ArrayAlignment:
 Enabled: true

Layout/ParameterAlignment:
 Enabled: true
Style/Documentation:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
Style/EachForSimpleLoop:
  Enabled: true
Style/AndOr:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented