AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"

  DisplayCopNames: true

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30


Style/Documentation:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
Style/EachForSimpleLoop:
  Enabled: true
Style/AndOr:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented